  /**
   * Creates an observable sequence from an incoming generator with no arguments
   * @example
   * var source = Observable.fromGenerator(function * () { yield 42; });
   * @param {Function} generatorFunction A function which is a generator.
   * @param {Scheduler} [scheduler] Optional scheduler for scheduling recursive calls. Defaults to current thread if not specified
   * @returns {Observable} An observable sequence which is generated by the generator.
   */  
  Observable.spawn = function (generatorFunction, scheduler) {
    return observableFromGenerator(observableFromGenerator, scheduler)();
  };
